variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - run

.base:
  image: gitlab-registry.cern.ch/muon-collider/mucoll-deploy/mucoll:2.8-patch2-el9

build:
  extends: .base
  stage: build
  script:
    - source /opt/setup_mucoll.sh || yes
    - ls
    - cmake -S . -B build
    - cmake --build build
  artifacts:
    name: build
    when: always
    paths:
      - $CI_PROJECT_DIR/build
    expire_in: 1 day
generate:
  extends: .base
  stage: build
  script:
    - curl https://nbartosi.web.cern.ch/tutorial_20230705/sim_Hbb/output_sim.slcio --output ./output_sim.slcio
  artifacts:
    name: input
    when: always
    paths:
      - $CI_PROJECT_DIR/output_sim.slcio
    expire_in: 1 day
run:
  extends: .base
  stage: run
  script:
    - source ci/safesource.sh source setup.sh build/
    - Marlin ${MYWORKSPACE}/example/actsseedckf_steer.xml --InitDD4hep.DD4hepXMLFile=${MUCOLL_GEO} --global.LCIOInputFiles=output_sim.slcio
  artifacts:
    name: output
    when: always
    paths:
      - $CI_PROJECT_DIR/actsseedckf.root
    expire_in: 30 day

